### ISSUE TITLE
vec_cbind() changes name unnecessarily

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#685] opened 2019-11-24 21:42 UTC
`...1` is a valid name so we shouldn't change it (but doesn't happen if it comes first)

``` r
library(vctrs)
library(tibble)

vec_cbind(
  tibble(x = 1), 
  tibble(...1 = 2)
)
#> New names:
#> * ...1 -> ...2
#> # A tibble: 1 x 2
#>       x  ...2
#>   <dbl> <dbl>
#> 1     1     2

vec_cbind(
  tibble(...1 = 2),
  tibble(x = 1)
)
#> # A tibble: 1 x 2
#>    ...1     x
#>   <dbl> <dbl>
#> 1     2     1
```

<sup>Created on 2019-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment] 2019-11-25 07:30
I thought this was on purpose, because `...i` should always indicate the position of repaired arguments, so they are always repaired as well.

Maybe repaired arguments should always be repaired first thing, and it's UB to further deal with them?

**Comment by hadley** [comment] 2019-11-25 08:31
But ...1 is a valid name so shouldn’t get repaired here, I think. @jennybc can confirm

**Comment by jennybc** [comment] 2019-11-25 16:13
I confirm what @lionel- says: the default name repair strategy is to strip positional suffixes that look like they were created by name repair and recompute them. There was an explicit reason for this but it's not top of mind. If it's important, I can try to recall/rederive.

I don't really think actual users will be attached to a specific `...j` name that was created through name repair.

The real origin of this issue is in tidyr, I think? If I'm right, I think we should re-analyze how name repair is (not) working in that motivating problem.

**Comment by jennybc** [comment] 2019-11-25 17:29
Also to shed some light on this:

> but doesn't happen if it comes first

I suspect it *does* happen. It gets stripped and then re-applied. And since it's in the first position the new name (suffix, really) is same as old name.

**Comment by hadley** [comment] 2019-11-25 20:26
It seems odd to me that name repair creates names that we don't consider to be ok, so they potentially get munged again. I will contemplate if tidyr needs to use a different default repair strategy, but the point of using this strategy was to avoid duplicate names.

**Comment by jennybc** [comment] 2019-11-25 21:31
> It seems odd to me that name repair creates names that we don't consider to be ok, so they potentially get munged again.

This 👆is a slightly misleading description, in the sense that all of these operations are bundled within the function that makes names unique. It's not separate steps. We never emit names that aren't `"unique"`.

This is addressed in [3.5.2 Roundtrips](https://principles.tidyverse.org/names-attribute.html#unique-names) (sorry there's no anchor at the level I need):

  1. Strip "our" suffixes.
  1. Identify elements that need repair (dupes, `""`, `..j`, `...`).
  1. Repair, based on current position.

This is why `...1` is repaired to `...3` in https://github.com/tidyverse/tidyr/issues/804, i.e. that column is moving from position 1 to 3.

I just re-read some of the discussion when developing name repair. Here's a glimpse of why we first strip suffixes that look like they arose from name repair.

If you **don't** do that, a naive application of suffixes can actually *create* duplicate names. Remember: there's no guarantee that the suffixes reflect current or output position, i.e. if we could be cbinding.

```
naive suffix-ing      
(no stripping)         pre-stripping
BEFORE  AFTER          BEFORE  AFTER
x       x              x       x
y*      y...2*         y       y...2
z       z              z       z
y*      y...4          y       y...4
y...2   y...2*         y...2   y...5

*indicates dupe
```

If we don't strip suffixes, we have to attempt to make unique, check again if unique, and continue appending until we're unique. It is possible to construct inputs that require several rounds of repair. Stripping suffixes seemed like a simple way to guarantee that the application of the suffixes doesn't create new dupes.

Re: https://github.com/tidyverse/tidyr/issues/804. It seems like no one should be explicitly specifying `.names_from = "...1"`, i.e. hard-coding a variable name that was created by automatic name repair. It seems like a case of this:

> When unique-ifying names, we assume that the input names have been repaired by the same strategy, i.e. that we are consuming dogfood. Therefore, pre-existing suffixes of the form `...j` are stripped, prior to (re-)constructing the suffixes. If this interacts poorly with your names, you need to take control of name repair.

But I also noted 😬

> JB: it is conceivable that this should be under the control of an argument, e.g. `dogfood = TRUE`, in the (currently unexported) function that does this.

**Comment by lionel-** [comment] 2019-11-26 12:24
Rather obscure edge case, but seems relevant: https://github.com/tidyverse/dplyr/issues/4551#issuecomment-558578514

The repaired names won't be repaired again if they start with dots.

**Comment by lionel-** [comment] 2022-09-13 12:26
Closing as confirmed on Slack.

**Closed by lionel-** 2022-09-13 12:26 UTC
Labels: theory, names
