### ISSUE TITLE
vec_ptype_common() cannot find a prototype when using (some) vectors created with {haven}

### ISSUE THREAD

**Issue by courtiol** [r-lib/vctrs#624] opened 2019-10-19 09:14 UTC
Hi all,

`{haven}` is a tidyverse :package: allowing -- among other things -- to deal with labelled variables, which SPSS users are used to work with. There are a little like usual R factors except that the labels remain attributes and the numbers corresponding to each factors remain of class numeric or integer. Although converting such labelled numerical variables into factors is always an option, some users prefer to keep them as is to do arithmetic on such variables, which is a usual practice in social science (e.g. for the analysis of Likert scores).

Although not a high profile one, it would be great if it would play along with others tidyverse packages.  I've tracked a small limitation that seems to be caused by `vctrs::vec_ptype_common()`. This limitation has the unfortunate consequence of preventing pivoting tibbles:

``` r
library(tidyverse)

foo <- factor(c(1, 2))
bar <- factor(c(1, 3))

vctrs::vec_ptype_common(foo, bar)
#> factor(0)
#> Levels: 1 2 3

tibble(x = foo, y = bar) %>%
  pivot_longer(everything())
#> # A tibble: 4 x 2
#>   name  value
#>   <chr> <fct>
#> 1 x     1    
#> 2 y     1    
#> 3 x     2    
#> 4 y     3


foo <- haven::labelled(c(1, 2), labels = c(a = 1, b = 2))
bar <- haven::labelled(c(1, 3), labels = c(a = 1, c = 3))

vctrs::vec_ptype_common(foo, bar)
#> No common type for `..1` <haven_labelled> and `..2` <haven_labelled>.

tibble(x = foo, y = bar) %>%
  pivot_longer(everything())
#> No common type for `x` <haven_labelled> and `y` <haven_labelled>.
```

<sup>Created on 2019-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2019-10-19 13:05
Duplicate of https://github.com/tidyverse/haven/issues/477 — this needs to be fixed in haven, not in vctrs.

**Closed by hadley** 2019-10-19 13:05 UTC
