### ISSUE TITLE
Return `c("tbl", "data.frame")` dfs to inherit from tibble print method

### ISSUE THREAD

**Issue by mikemahoney218** [r-lib/vctrs#1632] opened 2022-08-29 22:37 UTC
Sorry to report this here when I suspect it's an issue with pillar, but this is where I noticed things and I don't know enough to debug further. When given perfectly normal tibbles, `vec_count()` produces corrupt data frames:

``` r
library(tibble)
library(vctrs)
#> 
#> Attaching package: 'vctrs'
#> The following object is masked from 'package:tibble':
#> 
#>     data_frame
data(Sacramento, package = "modeldata")
vec_count(Sacramento["city"])
#> Warning in format.data.frame(if (omit) x[seq_len(n0), , drop = FALSE] else x, :
#> corrupt data frame: columns will be truncated or padded with NAs
#>                      key count
#> 1     # A tibble: 37 × 1   438
#> 2        city              114
#> 3        <fct>              48
#> 4      1 SACRAMENTO         35
#> 5      2 ELK_GROVE          33
#> 6      3 ROSEVILLE          28
#> 7      4 CITRUS_HEIGHTS     23
#> 8      5 ANTELOPE           22
#> 9      6 RANCHO_CORDOVA     21
#> 10     7 EL_DORADO_HILLS    21
#> 11     8 LINCOLN            20
#> 12     9 GALT               17
#> 13    10 NORTH_HIGHLANDS    17
#> 14 # … with 27 more rows    13
#> 15                  <NA>    11
#> 16                  <NA>    10
#> 17                  <NA>     9
#> 18                  <NA>     9
#> 19                  <NA>     5
#> 20                  <NA>     5
#> 21                  <NA>     4
#> 22                  <NA>     4
#> 23                  <NA>     3
#> 24                  <NA>     3
#> 25                  <NA>     3
#> 26                  <NA>     3
#> 27                  <NA>     2
#> 28                  <NA>     2
#> 29                  <NA>     1
#> 30                  <NA>     1
#> 31                  <NA>     1
#> 32                  <NA>     1
#> 33                  <NA>     1
#> 34                  <NA>     1
#> 35                  <NA>     1
#> 36                  <NA>     1
#> 37                  <NA>     1
```

<sup>Created on 2022-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.0 (2022-04-22)
#>  os       Ubuntu 20.04.4 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/New_York
#>  date     2022-08-29
#>  pandoc   2.18 @ /usr/lib/rstudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.0)
#>  evaluate      0.16    2022-08-09 [1] CRAN (R 4.2.0)
#>  fansi         1.0.3   2022-03-24 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0   2021-01-25 [2] CRAN (R 4.1.1)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.0)
#>  knitr         1.40    2022-08-24 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
#>  pillar        1.8.1   2022-08-19 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3   2019-09-22 [2] CRAN (R 4.0.2)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.0  2022-06-28 [1] CRAN (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.4   2022-07-12 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.16    2022-08-24 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.0)
#>  stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.0)
#>  styler        1.7.0   2022-03-13 [1] CRAN (R 4.2.0)
#>  tibble      * 3.1.8   2022-07-22 [1] CRAN (R 4.2.0)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.0)
#>  vctrs       * 0.4.1   2022-04-13 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.32    2022-08-10 [1] CRAN (R 4.2.0)
#>  yaml          2.3.5   2022-02-21 [1] CRAN (R 4.2.0)
#> 
#>  [1] /home/mikemahoney218/R/x86_64-pc-linux-gnu-library/4.2
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

And with development versions of pillar, tibble, and vctrs:

``` r
library(tibble)
library(vctrs)
#> 
#> Attaching package: 'vctrs'
#> The following object is masked from 'package:tibble':
#> 
#>     data_frame
data(Sacramento, package = "modeldata")
vec_count(Sacramento["city"])
#> Warning in format.data.frame(if (omit) x[seq_len(n0), , drop = FALSE] else x, :
#> corrupt data frame: columns will be truncated or padded with NAs
#>                      key count
#> 1     # A tibble: 37 × 1   438
#> 2        city              114
#> 3        <fct>              48
#> 4      1 SACRAMENTO         35
#> 5      2 ELK_GROVE          33
#> 6      3 ROSEVILLE          28
#> 7      4 CITRUS_HEIGHTS     23
#> 8      5 ANTELOPE           22
#> 9      6 RANCHO_CORDOVA     21
#> 10     7 EL_DORADO_HILLS    21
#> 11     8 LINCOLN            20
#> 12     9 NORTH_HIGHLANDS    17
#> 13    10 GALT               17
#> 14 # … with 27 more rows    13
#> 15                  <NA>    11
#> 16                  <NA>    10
#> 17                  <NA>     9
#> 18                  <NA>     9
#> 19                  <NA>     5
#> 20                  <NA>     5
#> 21                  <NA>     4
#> 22                  <NA>     4
#> 23                  <NA>     3
#> 24                  <NA>     3
#> 25                  <NA>     3
#> 26                  <NA>     3
#> 27                  <NA>     2
#> 28                  <NA>     2
#> 29                  <NA>     1
#> 30                  <NA>     1
#> 31                  <NA>     1
#> 32                  <NA>     1
#> 33                  <NA>     1
#> 34                  <NA>     1
#> 35                  <NA>     1
#> 36                  <NA>     1
#> 37                  <NA>     1
```

<sup>Created on 2022-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.0 (2022-04-22)
#>  os       Ubuntu 20.04.4 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/New_York
#>  date     2022-08-29
#>  pandoc   2.18 @ /usr/lib/rstudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  cli           3.3.0      2022-04-25 [1] CRAN (R 4.2.0)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.2.0)
#>  evaluate      0.16       2022-08-09 [1] CRAN (R 4.2.0)
#>  fansi         1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0      2021-01-25 [2] CRAN (R 4.1.1)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
#>  glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.3      2022-07-18 [1] CRAN (R 4.2.0)
#>  knitr         1.40       2022-08-24 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
#>  pillar        1.8.1.9000 2022-08-29 [1] Github (r-lib/pillar@12eeed2)
#>  pkgconfig     2.0.3      2019-09-22 [2] CRAN (R 4.0.2)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0     2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.0     2022-06-28 [1] CRAN (R 4.2.0)
#>  reprex        2.0.2      2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.4      2022-07-12 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.16       2022-08-24 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
#>  stringi       1.7.8      2022-07-11 [1] CRAN (R 4.2.0)
#>  stringr       1.4.1      2022-08-20 [1] CRAN (R 4.2.0)
#>  styler        1.7.0      2022-03-13 [1] CRAN (R 4.2.0)
#>  tibble      * 3.1.8.9001 2022-08-29 [1] Github (tidyverse/tibble@82ba62b)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.2.0)
#>  vctrs       * 0.4.1.9000 2022-08-29 [1] Github (r-lib/vctrs@78a97da)
#>  withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.32       2022-08-10 [1] CRAN (R 4.2.0)
#>  yaml          2.3.5      2022-02-21 [1] CRAN (R 4.2.0)
#> 
#>  [1] /home/mikemahoney218/R/x86_64-pc-linux-gnu-library/4.2
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by DavisVaughan** [comment] 2022-08-29 22:40
it isn't really corrupt, the data frame print method in base R is just a bit broken. just convert it to a tibble when you need to print it, it otherwise works fine as a data frame

``` r
library(tibble)
#> Warning: package 'tibble' was built under R version 3.6.2
library(vctrs)
#> 
#> Attaching package: 'vctrs'
#> The following object is masked from 'package:tibble':
#> 
#>     data_frame
data(Sacramento, package = "modeldata")
as_tibble(vec_count(Sacramento["city"]))
#> # A tibble: 37 × 2
#>    key$city        count
#>    <fct>           <int>
#>  1 SACRAMENTO        438
#>  2 ELK_GROVE         114
#>  3 ROSEVILLE          48
#>  4 CITRUS_HEIGHTS     35
#>  5 ANTELOPE           33
#>  6 RANCHO_CORDOVA     28
#>  7 EL_DORADO_HILLS    23
#>  8 LINCOLN            22
#>  9 NORTH_HIGHLANDS    21
#> 10 GALT               21
#> # … with 27 more rows
```

<sup>Created on 2022-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mikemahoney218** [comment] 2022-08-29 22:41
Bizarre! Thanks.

**Comment by lionel-** [comment] 2022-08-30 09:58
We should return data frames of class `c("tbl", "data.frame")` so they print correctly when pillar (IIRC) is installed.

**Comment by DavisVaughan** [comment] 2022-08-30 13:01
I have been somewhat against this. I want my data frames to print like data frames, and tibbles to print like tibbles :/

**Comment by DavisVaughan** [comment] 2022-08-30 13:02
Regardless I think it becomes a duplicate of https://github.com/r-lib/vctrs/issues/1383, so we should consider `vec_count()` if/when we tackle it there

**Comment by lionel-** [comment] 2022-08-30 13:05
I think this is just a matter of getting used to proper formatting of bare data frames. Sounds good regarding tackling this in the other issue.

**Closed by lionel-** 2022-08-30 13:05 UTC
