### ISSUE TITLE
vec_rbind cannot combine bit64::integer64 with other numeric types

### ISSUE THREAD

**Issue by schuemie** [r-lib/vctrs#1309] opened 2021-01-13 14:43 UTC
`vec_rbind` allows combine various numeric types, except when one of the types is `bit64::integer64`. For consistency, it would help if `integer64` was treated similar to for example `integer`.

reprex:

```r
suppressPackageStartupMessages({
  library(vctrs)
  library(tibble)
  library(bit64)
})

vec_rbind(
  tibble(a = as.numeric(1)), 
  tibble(a = as.integer64(2))
)
#> Error: Can't combine `..1$a` <double> and `..2$a` <integer64>.

vec_c(as.numeric(1), as.integer64(2))
#> Error: Can't combine `..1` <double> and `..2` <integer64>.
vec_ptype2(as.numeric(1), as.integer64(2))
#> Error: Can't combine <double> and <integer64>.
```

This issue was [originally posted under dplyr](https://github.com/tidyverse/dplyr/issues/5684).

**Comment by DavisVaughan** [comment] 2021-01-14 14:22
> For consistency, it would help if integer64 was treated similar to for example integer.

I don't think that we can do that. bit64 coerces doubles to integer64, while R coerces integers to double. So having vctrs coerce integer64 to double would go against what the bit64 designer had in mind.

```r
library(bit64)

x <- 1.5
y <- bit64::as.integer64(2)
z <- 2L

# coerces to bit64
c(y, x)
#> integer64
#> [1] 2 1

# coerces to double
c(z, x)
#> [1] 2.0 1.5
```

Additionally, as soon as you start working with an integer64 value >2^53 - 1, then it can't be directly converted to a double without potential loss of precision. This goes against the spirit of `vec_cast()`, which generally tries to preserve all information, or die trying.

``` r
library(bit64)

# 2^53 - 1
x <- "9007199254740991"
x64 <- bit64::as.integer64(x)

# 2^53 + 1
y <- "9007199254740993"
y64 <- bit64::as.integer64(y)

options(digits = 22)

x64
#> integer64
#> [1] 9007199254740991
as.double(x64)
#> [1] 9007199254740991

# OH NO!
y64
#> integer64
#> [1] 9007199254740993
as.double(y64)
#> Warning in as.double.integer64(y64): integer precision lost while converting to
#> double
#> [1] 9007199254740992
```

If you want this behavior, I would encourage explicitly converting your `a` columns directly to integer64 or double before combining.

**Comment by lionel-** [comment] 2022-09-13 13:34
Duplicate of #1542. It's a newer thread but with more discussion so I'm closing here.

**Closed by lionel-** 2022-09-13 13:34 UTC
Labels: type:integer64
