### ISSUE TITLE
vec_match() fails with 0-col data frame

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#199] opened 2019-02-21 20:13 UTC
``` r
library(vctrs)
vec_match(tibble::tibble(.rows = 3), tibble::tibble())
#> Error: Can't subset with `[` using an object of class NULL.
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by yutannihilation** [comment] 2019-02-21 22:32
I'm closing #179 as a duplicate of this.

**Comment by hadley** [comment] 2019-02-26 22:05
Becauase `vec_type2()` creates a data frame with `NULL` names here:

``` r
library(vctrs)
out <- vec_type2(tibble::tibble(.rows = 3), tibble::tibble())
names(out)
#> NULL
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Closed** 2019-02-26 22:37 UTC
