### ISSUE TITLE
When I use unnest function to boostrap, the error shows and no solution on the internet. please 

### ISSUE THREAD

**Issue by kingsun9** [r-lib/vctrs#1842] opened 2023-05-28 12:03 UTC
Error in `stop_native_implementation()`:
! `vec_ptype2.integer.integer()` is implemented at C level.
  This R function is purely indicative and should never be called.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex and the full
  backtrace.

**Comment by kingsun9** [comment] 2023-05-28 12:03
Backtrace:
     ▆
  1. ├─... %>% head()
  2. ├─utils::head(.)
  3. ├─tidyr::unnest(., cols = c(data))
  4. ├─tidyr:::unnest.data.frame(., cols = c(data))
  5. │ └─tidyr::unchop(...)
  6. │   └─tidyr:::df_unchop(...)
  7. │     └─vctrs::list_unchop(col, ptype = col_ptype)
  8. └─vctrs (local) `<fn>`()
  9.   └─vctrs::vec_default_ptype2(...)
 10.     └─vctrs:::vec_ptype2_df_fallback(...)
 11.       └─vctrs:::vec_ptype2_params(...)
 12.         └─vctrs:::vec_ptype2_opts(...)
 13.           └─vctrs (local) `<fn>`()
 14.             └─vctrs:::vec_ptype2.integer.integer(...)
 15.               └─vctrs:::stop_native_implementation("vec_ptype2.integer.integer")
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.

**Comment by DavisVaughan** [comment] 2023-05-30 13:36
You likely have integer vectors with attributes attached to them. If you remove the attributes before unnesting then it should work. 

This is a duplicate of https://github.com/r-lib/vctrs/issues/1300 so I'm going to close this one

**Closed by DavisVaughan** 2023-05-30 13:36 UTC
