### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by jfunction** [r-lib/vctrs#1752] opened 2022-12-07 17:01 UTC
I would have dug deeper or provided more detail but I'm exhausted and on a tight deadline - I wanted to at least report it though. This came up when using the `googledrive` package with a faulty assumption that my dribble was non-empty so I assumed the `hoist` actually gave something with `baz` in it; I've simplified it a bit for the reprex (may be possible to make it even more simple). I would have expected a more descriptive error in this case: 
``` r
library(tidyverse)
tibble(foo=1,bar=list()) %>%
  hoist(bar, 'baz') %>%
  filter(baz==1)
#> Error in `vec_slice()`:
#> ! Unexpected `NULL`.
#> i In file 'slice.c' at line 322.
#> i This is an internal error that was detected in the vctrs package.
#>   Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://https://tidyverse.org/help/>) and the full backtrace.
```

<sup>Created on 2022-12-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment] 2022-12-21 20:04
What versions of dplyr, vctrs, tidyr do you have?

And is the error in `filter()` or `hoist()`?

I can't reproduce with the CRAN version of all of these, suggesting we may have fixed this already.

``` r
library(tidyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tibble(foo=1,bar=list()) %>%
  hoist(bar, 'baz')
#> # A tibble: 0 × 1
#> # … with 1 variable: foo <dbl>

tibble(foo=1,bar=list()) %>%
  hoist(bar, 'baz') %>%
  filter(baz==1)
#> Error in `filter()`:
#> ! Problem while computing `..1 = baz == 1`.
#> Caused by error in `mask$eval_all_filter()`:
#> ! object 'baz' not found

#> Backtrace:
#>      ▆
#>   1. ├─tibble(foo = 1, bar = list()) %>% hoist(bar, "baz") %>% ...
#>   2. ├─dplyr::filter(., baz == 1)
#>   3. ├─dplyr:::filter.data.frame(., baz == 1)
#>   4. │ └─dplyr:::filter_rows(.data, ..., caller_env = caller_env())
#>   5. │   └─dplyr:::filter_eval(dots, mask = mask, error_call = error_call)
#>   6. │     ├─base::withCallingHandlers(...)
#>   7. │     └─mask$eval_all_filter(dots, env_filter)
#>   8. └─base::.handleSimpleError(...)
#>   9.   └─dplyr (local) h(simpleError(msg, call))
#>  10.     └─rlang::abort(bullets, call = error_call, parent = skip_internal_condition(e))
```

<sup>Created on 2022-12-21 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by jfunction** [comment] 2022-12-21 20:33
Thanks for looking at this. I just got loadshedding here so no power for a bit, but I had a quick look and noted the hoist is returning a tibble with 2 columns rather than the 1 I see yours is returning. I'm on 1.1.4 for tidyr. I will look into it tomorrow and answer your questions more completely if that clue isn't enough.

**Comment by DavisVaughan** [comment] 2022-12-21 20:37
Ok with tidyr 1.1.4 `hoist()` was a little broken and badly returned a `NULL` column.

``` r
library(tidyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

tibble(foo=1,bar=list()) %>%
  hoist(bar, 'baz') %>%
  str()
#> tibble [0 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ foo: num(0) 
#>  $ baz: NULL
```

It now doesn't return any column, which isn't necessarily better (it possibly should return an empty logical column), but it does mean that this bug is technically fixed by just updating tidyr so I'm going to close here

**Closed by DavisVaughan** 2022-12-21 20:37 UTC
Labels: reprex
