### ISSUE TITLE
Expose vec_hash()

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#664] opened 2019-11-13 20:17 UTC
It would be useful in ggplot2 where we're currently using digest just to compute a unique id for the legends (based on a number of components).

**Comment by DavisVaughan** [comment] 2019-11-13 20:25
From a reproducibility standpoint does it matter at all that strings won't return the same hash from one R session to the next?

``` r
vctrs:::vec_hash(1)
#> [1] 00 c1 04 29

vctrs:::vec_hash("hello")
#> [1] b9 2b 15 61
```

_Restart R_

``` r
vctrs:::vec_hash(1)
#> [1] 00 c1 04 29

vctrs:::vec_hash("hello")
#> [1] 58 95 c5 94
```

**Comment by hadley** [comment] 2019-11-13 20:28
That's #107 (and fixing it would also let us eliminate digest)

**Comment by lionel-** [comment] 2019-11-14 07:55
I feel rather uneasy about exposing `vec_hash()`:

- The algorithm is still unstable. I don't think we should commit to reproducibility across sessions yet.

- It's unclear what are the properties of our hashes compared to those provided by digest (likelihood of uniqueness?).

- `vec_hash()` doesn't seem that useful. Shouldn't it be `obj_hash()` that should be exported? And then it doesn't feel like a vctrs function.

**Comment by hadley** [comment] 2019-11-14 13:19
For most of the places we need it, I don't think any of those properties are particularly problematic. What if we just mark it as experimental and `@keywords internal`.

**Comment by lionel-** [comment] 2019-11-14 14:00
Marking as experimental and internal sounds good. I still find it odd that we expose `vec_hash()` instead of `obj_hash()`.

> For most of the places we need it, I don't think any of those properties are particularly problematic.

What are the clear assumptions that users can make about the returned hashes? This is fuzzy to me. I think this should be documented, especially if used in important packages like ggplot2.

**Comment by hadley** [comment] 2019-11-14 18:10
ggplot2 is just using it to come up with a unique identifier for legends, so it's not exactly mission critical.

**Comment by lionel-** [comment] 2019-11-14 20:51
It seems like we should document that this is a stopgap tool, no strong reproducibility assumptions can be made, and the hash results should not be tested in unit tests as they might change without warning.

Any objections to exporting `obj_hash()` instead of `vec_hash()`? The former makes more sense regarding the intended usage.

**Comment by hadley** [comment] 2019-11-14 22:00
Fine with me

**Closed** 2021-03-03 17:25 UTC
Labels: feature, op:equal-compare-hash
