### ISSUE TITLE
Some classes still need `vec_proxy_equal()`

### ISSUE THREAD

**Issue by jessesadler** [r-lib/vctrs#375] opened 2019-06-03 22:06 UTC
A change I noticed from `vec_proxy_equal()` in CRAN version to current implementation with `vec_proxy()` is that `vec_proxy_compare()` methods such as `sort()`, `max()` return the values from `vec_proxy(x)` and not `x`. The CRAN version returns the values of `x`, which seems to me to be preferable.

This makes it difficult to which value is equal to which index in x. It also causes unexpected differences in other places such as subsetting.

You can see an example of this in the S3 vignette with the Rational class. I think that the below provides the minimum to show this.

Thanks

```R
library(vctrs)

new_rational <- function(n = integer(), d = integer()) {
  vec_assert(n, ptype = integer())
  vec_assert(d, ptype = integer())
  
  new_rcrd(list(n = n, d = d), class = "vctrs_rational")
}

rational <- function(n, d) {
  c(n, d) %<-% vec_cast_common(n, d, .to = integer())
  c(n, d) %<-% vec_recycle_common(n, d)
  
  new_rational(n, d)
}

format.vctrs_rational <- function(x, ...) {
  # Access fields
  n <- field(x, "n")
  d <- field(x, "d")
  
  out <- paste0(n, "/", d)
  # Dealing with NA: Underlying data still present
  out[is.na(n) | is.na(d)] <- NA
  
  out
}

gcd <- function(x, y) {
  r <- x %% y
  ifelse(r, gcd(y, r), y)
}

vec_proxy.vctrs_rational <- function(x) {
  n <- field(x, "n")
  d <- field(x, "d")
  gcd <- gcd(n, d)
  
  data.frame(n = n / gcd, d = d / gcd)
}

vec_proxy_compare.vctrs_rational <- function(x) {
  field(x, "n") / field(x, "d")
}

# Changed slightly from S3 vignette to more clearly show issue
x <- rational(c(1, 2, 1, 2, 6), c(1, 1, 2, 2, 2))

# Sort works but shows values from vec_proxy(x) instead of from x
sort(x)

# Subsetting applies vec_proxy, and so though answers are equal, they are not the same
max(x)
max(x[-3])

# Compare
identical(max(x), max(x))
identical(max(x), max(x[-3]))
```

**Comment by hadley** [comment] 2019-06-03 22:08
I think this is a duplicate of #251, but @lionel- will confirm.

**Comment by jessesadler** [comment] 2019-06-03 23:07
Thanks @hadley. I finally got some time port my non-decimal currency package (debkeepr) over to vctrs, so I am in the midst of finding out what works and what does not. I will try not to open too many duplicate issues. 😉

**Comment by lionel-** [comment] 2019-06-04 08:04
I think this is a case where the equality proxy needs to be different from the vector proxy. Currently, the vector proxy is changing the values (in case they are compared) and so can't be restored.

**Comment by jessesadler** [comment] 2019-06-04 19:35
Thanks. That makes sense. This was also causing other issues in my code where `vec_proxy()` is implicitly called and so returning incorrect values.

**Closed** 2019-06-05 12:46 UTC
Labels: op:proxy, op:restore
