### ISSUE TITLE
`Error: `vec_ptype2.integer.integer()` is implemented at C level`

### ISSUE THREAD

**Issue by iago-pssjd** [r-lib/vctrs#1380] opened 2021-05-12 11:13 UTC
Not sure why it is failing:
```r
vctrs::vec_rbind(structure(list(a = structure(10100001L,  class = "integer")), class = "data.frame"),
                 structure(list(a = structure(10100001L,  class = "integer")), class = "data.frame"))
Error: `vec_ptype2.integer.integer()` is implemented at C level.
This R function is purely indicative and should never be called.
Run `rlang::last_error()` to see where the error occurred.
```
(so failing in `dplyr::bind_rows` and `purrr::map_dfr`)

**Comment by iago-pssjd** [comment] 2021-05-12 11:23
If I use instead `base::rbind`, in a posterior step merging through a `full_join` I get also this error.

**Comment by DavisVaughan** [comment] 2021-05-12 13:16
Duplicate of https://github.com/r-lib/vctrs/issues/1300

In the meantime, if you can get rid of the explicit `"integer"` class attribute, it should work:

``` r
# doesnt work
df <- data.frame(x = structure(10100001L, class = "integer"))

vctrs::vec_rbind(df, df)
#> Error: `vec_ptype2.integer.integer()` is implemented at C level.
#> This R function is purely indicative and should never be called.

# works
df <- data.frame(x = 10100001L)

vctrs::vec_rbind(df, df)
#>          x
#> 1 10100001
#> 2 10100001
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DavisVaughan** [comment] 2021-05-18 17:35
@iago-pssjd do you know how you generated an integer with this structure? Were you calling an API of some kind that returned this data to you?

**Comment by iago-pssjd** [comment] 2021-05-19 06:47
@DavisVaughan  This integer structure is included in data frames downloaded from a website where data is stored and processed through OPAL (you might look at https://github.com/obiba/opal or https://opaldoc.obiba.org/en/latest/).

I hope this answer your question.

**Comment by DavisVaughan** [comment] 2021-05-19 13:08
Did the data come through the opalr R package?

**Comment by iago-pssjd** [comment] 2021-05-19 14:06
Yes, it did.

**Comment by DavisVaughan** [comment] 2021-05-20 11:47
@iago-pssjd they seem to have fixed this upstream, can you confirm? https://github.com/obiba/opal/issues/3636#event-4771781461

**Comment by iago-pssjd** [comment] 2021-06-03 09:13
@DavisVaughan  Thanks! Actually I cannot upload the OPAL version used in the source website (it does not depend on me) and AFAIK it will remain the same, but I trust this upstream is fixed.

**Comment by DavisVaughan** [comment] 2021-06-03 12:33
Ok! I'll close this since it is a duplicate of #1300 and this specific issue with OPAL is hopefully fixed

**Closed by DavisVaughan** 2021-06-03 12:33 UTC
