### ISSUE TITLE
Error when installing: 'is_character' is not an exported object from 'namespace:rlang'

### ISSUE THREAD

**Issue by gui-salome** [r-lib/vctrs#1661] opened 2022-09-14 21:40 UTC
I'm installing `vctrs` (and other packages) with `renv::restore`. The version of `vctrs` being installed is `0.3.4`, but it fails with the following error:
<img width="696" alt="Screen Shot 2022-09-14 at 5 33 13 PM" src="https://user-images.githubusercontent.com/68299186/190266539-6daa3b2b-9d7e-4afa-b1c8-000c29b812b5.png">
The error is related to `rlang`, and the version of `rlang` installed is. `1.0.5`. 
I looked in the [DESCRIPTION](https://github.com/r-lib/vctrs/blob/ee5e377bffea06d9ed53e2240aaa11d106c6a666/DESCRIPTION) file for `vctrs=0.3.4`, and the requirements for `rlang` are `>= 0.4.7`. In this case, that requirement is satisfied, and although the package was probably built with a much older version of `rlang` in mind, the `is_character` function is [still exported](https://github.com/r-lib/rlang/blob/d0b04ff87a7e0f3ebf1411ed322bd2c3a4eb25d5/NAMESPACE#L322) in `1.0.5`. 

Anyone has any idea on what could be causing this error?

**Comment by DavisVaughan** [comment] 2022-09-15 13:10
Duplicate of https://github.com/r-lib/rlang/issues/1482

**Closed by DavisVaughan** 2022-09-15 13:10 UTC

**Comment by gaborcsardi** [comment] 2022-09-15 13:32
When I install vctrs 0.3.4 with rlang 1.0.4 I see 
```
Warning: The package `vctrs` (>= 0.3.8) is required as of rlang 1.0.0.
```
So I doubt that vctrs 0.3.4 will work with rlang 1.0.x.

**Comment by shenweiyan** [comment] 2022-09-20 08:50
I got the same error with R-4.0.3, and hope this will be fixed soon.

**Comment by lionel-** [comment] 2022-09-20 09:10
I think you can just remove vctrs from your library and reinstall it.

**Comment by shenweiyan** [comment] 2022-09-20 09:24
> I think you can just remove vctrs from your library and reinstall it.

I tried it but still getting the same error.

**Comment by lionel-** [comment] 2022-09-20 13:36
I'm assuming you're on Linux like the other users that have this problem? If so you may have to remove the package installed by your distribution.

**Comment by gaborcsardi** [comment] 2022-09-20 13:44
@lionel- Don't you need to install dev rlang to fix this?

**Comment by gui-salome** [comment] 2022-09-20 13:58
This is on `ubuntu` (via Github actions).

**Comment by lionel-** [comment] 2022-09-20 14:27
@lionel- I think you don't need to, if there is no old vctrs installed in the active library.
