### ISSUE TITLE
Move zeallot to suggests and don't export %<-%

### ISSUE THREAD

**Issue by traversc** [r-lib/vctrs#558] opened 2019-09-03 00:42 UTC
I use both `zeallot` and `future` packages quite a bit in my day to day, but both packages lay claim to the `%<-%` operator and conflict.  

Usually I would unload one or the other and then reload it in the correct order, but that's more difficult now since `vctrs` (and anything downstream) would need to be unloaded.  

There's an analogy to the `%<%` operator from `magrittr` but the difference here is that there are two separate and both popular usages of the `%<-%` operator.

**Comment by hadley** [comment] 2019-09-03 12:18
(FWIW the problem is not importing zeallot but re-exporting `%<-%`)

**Comment by hadley** [comment] 2019-11-13 23:02
I think we're going to move zealot to suggests because we're moving towards vctrs being a zero dependency package.

**Comment by hadley** [comment] 2019-11-24 21:42
@DavisVaughan didn't you do this?

**Comment by DavisVaughan** [comment] 2019-11-24 21:57
Yes!

**Closed by DavisVaughan** 2019-11-24 21:57 UTC
