### ISSUE TITLE
Unhelpful error when vectors_assert()'s input has attribute

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/vctrs#1603] opened 2022-08-09 11:44 UTC
``` r
a <- character()
attr(a, "foo") <- "bar"
vctrs::vec_assert(a, character())
#> Error:
#> ! `a` must be a vector with type <character>.
#> Instead, it has type <character>.
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Note that here `vec_ptype(a)`, or just `a` will display the attribute, but the print method for tibble and data.frame don't show them, so debugging this is not obvious ({waldo} helped).

On the other hand `vec_cast()` doesn't fail, but doesn't remove the attribute :  

``` r
vctrs::vec_cast(a, character())
#> character(0)
#> attr(,"foo")
#> [1] "bar"
```

It seems to me that if vec_assert() fails (keep behaviour with better error) vec_cast() might not fail but should strip the attribute, and that if vec_assert() doesn't fail (new behaviour) vec_cast() could stay as it is.

**Comment by billdenney** [comment] 2023-03-06 21:50
This appears to be a duplicate of #1157

**Closed** 2023-03-07 13:44 UTC
