### ISSUE TITLE
Create a pseudo-namespace for the c `reduce()` function

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/vctrs#862] opened 2020-02-25 20:43 UTC
The name is common enough that it clashes with functions linked in from other libraries. For example, the sf package could link to this:
https://github.com/OSGeo/gdal/blob/master/gdal/frmts/grib/degrib/g2clib/reduce.c

**Comment by lionel-** [comment] 2020-02-25 20:58
Dynamically loaded libraries are namespaced by design. To look a symbol up, you need the handle to the loaded library in addition to the symbol, and the symbol is only looked up in that shared object. If that were not the case, we'd have countless symbol conflicts in the package ecosystem.

See for example https://linux.die.net/man/3/dlopen used by R's dynamic loader on Linux.

**Comment by michaelquinn32** [comment] 2020-02-25 21:18
Thanks for pointing that out! I'm using R in an environment where everything is statically linked. Tests of the newest version of sf and tidyr would fail on memory not mapped errors because of this specific issue.

**Comment by lionel-** [comment] 2020-02-25 21:26
That's interesting, could you please give more details about this environment? To what extent is this environment viable? I can't imagine it's compatible with many CRAN packages.

It seems like to support such environments we'd need to revise our coding standards altogether, and add much friction in our programming!

**Comment by lionel-** [comment] 2020-02-25 21:38
I'm pretty sure there are symbol clashes in the shared libs of rlang and vctrs in the `r_` pseudo-namespace. Are you sure namespacing `reduce()` is sufficient?

**Comment by michaelquinn32** [comment] 2020-02-25 21:52
I work at Google, and we have thousands of packages running tests under CI. This is a less common issue than you'd think. Running tests of vctrs and tidyr against everything we have in CI, this was the only issue that came up.

We are using the fact that common R functions have a prefixed version to avoid clashes with other common functions defined in C (using the prefixed versions throughout). For C++, we make heavy use of namespaces.

**Comment by lionel-** [comment] 2020-02-26 07:16
What environment does your CI use? How and where does the static linking occur? Is there any OS/environment with the same mechanism that we can try or inspect? How does a symbol clash manifest, silent masking, warning, or error?

I don't understand how `reduce` could be the only symbol clash if you link statically to all shared objects of packages. I'm not necessarily opposed to merging your PR, but I would like to fully understand the problem first. I suspect it will be the first of many PRs unless we change our coding practices. I really would prefer to avoid many PRs or changing our coding practices, if possible.

**Comment by lionel-** [comment] 2020-02-26 07:38
Would it help if we added `-fvisibility=hidden` to our `CFLAGS`, and explicitly mark exposed functions with `__attribute__((__visibility__("default")))`? This would be a bit burdensome because compilation flags are generally not portable and we might need to add those from a `configure` script, and we'd need to use a macro for exported symbols. I would prefer this option than thinking about your PR every time I create a new symbol in a package though ;)

**Comment by lionel-** [comment] 2020-02-26 07:44
oh it looks like R has support for exactly that! So it will be easy to switch to explictly exported symbols: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Controlling-visibility

Does your environment have a compiler that support the visibility flags?

**Comment by lionel-** [comment] 2020-02-26 09:26
Are you perhaps _dynamically_ linking instead of statically? As I understand the former will use the first symbol discovered in a shared library, while the latter reports an error. That would explain that you found few problems, but that seems like an extremely fragile approach. The collision resolution depends on the order in which the packages are linked. Also functions like `r_env_get()` have the same signature and behaviour in both rlang and vctrs, but in general there's no guarantee about anything.

**Comment by michaelquinn32** [comment] 2020-02-26 19:04
> On CI:
We have our own CI system:
https://www.youtube.com/watch?v=KH2_sB1A6lA

Each test is a statically linked object containing what it needs to run itself. It doesn't have to link to every R extension. The space for possible collisions isn't especially big in R.

There's

- R itself (which we use prefixes for to have a namespace-like thing)
- Any user-written extension. All of our C++ extensions are using namespaces; they're pretty common in R outside google too.
- Dependencies; Only a few R extensions have big stacks of dependencies. sf is one example.

> On the visibility issues:
We don't use the same build system as you. But we do build R the same way we build everything else at Google.
https://www.youtube.com/watch?v=6GCDfoAOKIY

To loop back a bit, R tests are statically linked binaries as defined within bazel. Setting everything in CFLAGS doesn't make too much sense, since we manually configure extensions. But this depends on the person who has configured the build, and these sometimes change during updates.

It's easier to think about namespaces instead.

> Are you dynamically linking?
No. I'm pretty sure that we're statically linking, which is why the GDAL reduce is colliding with the vctrs reduce. This is a common issue at Google:
https://google.github.io/styleguide/cppguide.html#Goals

I think the broader solutions, from the practices of coding standards:
- C++: use namespaces: https://google.github.io/styleguide/cppguide.html#Namespaces
- C: Consider pseudo-namespaces to avoid possible collisions.

Let me know if there are other ways that I can help!

**Comment by michaelquinn32** [comment] 2020-02-26 19:31
Not sure if github over mail handles updates correctly, but the first version of my message above needed more nuance.

**Comment by hadley** [comment] 2020-02-26 19:42
@michaelquinn32 it does not — and thanks for all the colour here. We'll definitely fix vctrs; we just want to fully understand the problem first.

**Comment by lionel-** [comment] 2020-02-27 10:50
Thanks a lot for the detailed explanation, it's very helpful.

> I think the broader solutions, from the practices of coding standards:
>
>     C++: use namespaces: https://google.github.io/styleguide/cppguide.html#Namespaces
>     C: Consider pseudo-namespaces to avoid possible collisions.

The R contract is that libraries are dynamically loaded, not linked. This is why the R API requires packages to go through `R_RegisterCCallable()` and `R_GetCCallable()` to access function pointers from foreign modules.

It seems to me that asking R projects to follow Google's coding standards is an uphill battle and a brittle approach. Even if you end up with a usable system now, any update to the internals might introduce breaking changes for you if the standard are not followed.

On a more personal note, I'd really prefer to avoid namespacing all my C code, especially for util functions that might have the same name but possibly different implementations across packages (this is a way of safely experimenting with the behaviour or interface of a function without committing to an API).


> Setting everything in CFLAGS doesn't make too much sense, since we manually configure extensions. But this depends on the person who has configured the build, and these sometimes change during updates.

Since you need to configure the build anyway, I think the explicit visibility approach has better prospects. Could you please try working with #870 and see if it fixes the symbol collision. If this works, this would be an easy and robust way of making any package compatible with your build system:

* On our end we set `C_VISIBILITY` in our Makevars to make sure we remain compatible with builds that use hidden visibility.

* On your end, just compile the library with `-fvisibility=hidden` (and possibly `-DHAVE_VISIBILITY_ATTRIBUTE` in case R wasn't configured with visibility support, which is the case on macOS).

**Comment by michaelquinn32** [comment] 2020-02-28 02:51
Thanks!

It looks like it might solve this issue for us. Or at least the test that required my patch is now passing. It might be a little bit before I can give you full feedback. The dev version of rlang is causing some other tests to fail (like in ggplot2 3.1), and I would like to wait for a CRAN release before I go through the process of trying to update our internal repos.

Still. Thank you so much for hearing me out and being so patient with me as I described the problem. I'm really happy to see this sorted out.

**Comment by lionel-** [comment] 2020-02-28 09:47
That's great to hear! I'll add support for hidden visibility in rlang too.

The ggplot2 failure will be fixed soon: https://github.com/tidyverse/ggplot2/pull/3842

**Closed** 2020-02-28 09:48 UTC
