### ISSUE TITLE
Installation error for the version under development on Windows 10

### ISSUE THREAD

**Issue by psychelzh** [r-lib/vctrs#342] opened 2019-05-20 06:08 UTC
Error message:

```
Error: package or namespace load failed for 'vctrs':
 .onLoad failed in loadNamespace() for 'vctrs', details:
  call: fun(libname, pkgname)
  error: 程序包'rlang_is_splice_box'不提供'rlang'这样的函数
错误: 载入失败
停止执行
ERROR: loading failed for 'x64'
* removing 'C:/Users/liang/Documents/R/win-library/3.6/vctrs'
* restoring previous 'C:/Users/liang/Documents/R/win-library/3.6/vctrs'
```
Session information:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.3.0          prettyunits_1.0.2 crayon_1.3.4      withr_2.1.2      
 [5] rprojroot_1.3-2   assertthat_0.2.1  R6_2.4.0          backports_1.1.4  
 [9] magrittr_1.5      cli_1.1.0         curl_3.3          remotes_2.0.4    
[13] rstudioapi_0.10   callr_3.2.0       tools_3.6.0       compiler_3.6.0   
[17] processx_3.3.1    pkgbuild_1.0.3
```

**Comment by lionel-** [comment] 2019-05-20 06:55
Duplicate of #331.

**Closed by lionel-** 2019-05-20 06:55 UTC
