### ISSUE TITLE
Issue with vctrs when using ggplot2 and gganimate

### ISSUE THREAD

**Issue by avrenli2** [r-lib/vctrs#1777] opened 2023-01-26 14:34 UTC
``Hello,
When I run the following code, it does not create the animated chart and returns warning messages.
I would be grateful for your help.

`library(ggplot2)
library(Rcpp)
library(gganimate)
library(gifski)
library(transformr)
library(quantmod)
CHAI <- getSymbols("SBUX" , from="2020-1-1" , to="2021-1-1" , auto.assign=F) 
CARTOON <- ggplot(CHAI, aes(y=SBUX.Close,x=index(CHAI)))+
  geom_area(color="pink", size=1.2 , fill="pink" , alpha=0.3)+
  geom_point(color="#8F157E", size=4)+
  labs(x="Time", y="Close Price")+
  theme_bw() + transition_reveal(index(CHAI))  

animate(CARTOON, duration=7 , fps = 30)
`

Below is the warning message, which is displayed 50+ times:
**Problem while converting geom to grob.
Error occurred in the 1st layer.
Caused by error in `unit()`:
! 'x' and 'units' must have length > 0**

**Comment by DavisVaughan** [comment] 2023-01-26 15:08
Duplicate of #1778

**Closed by DavisVaughan** 2023-01-26 15:08 UTC
